# Site settings
title: SESYNC
subtitle: Site Template
email: itrequests@sesync.org
description: "SESYNC Technical Blog"
copyright: "&copy; National Socio-Environmental Synthesis Center (SESYNC)<br>1 Park Place, Suite 300, Annapolis, MD 21401"
# Build settings
markdown: kramdown
